import type { Equipment, Exercise, TemplateItem, WorkoutTemplate } from './types'
import type { TemplateId } from '../domain/types'

// Catalogue data from SPEZIFIKATION.md sections 2, 4 and 5. Contains no
// personal data: profile values are entered in the app on first start.

export const SEED_EQUIPMENT: Equipment[] = [
  {
    id: 'dumbbell',
    nameDe: 'Kurzhanteln',
    count: 2,
    barWeightKg: 2.3,
    plates: [
      { weightKg: 2, count: 4 },
      { weightKg: 1.25, count: 4 },
      { weightKg: 1, count: 8 },
    ],
    maxPlatesPerSide: 4,
  },
  { id: 'pullup_bar', nameDe: 'Klimmzugstange', count: 1, barWeightKg: null, plates: [], maxPlatesPerSide: null },
  { id: 'mat', nameDe: 'Trainingsmatte', count: 1, barWeightKg: null, plates: [], maxPlatesPerSide: null },
  { id: 'bike', nameDe: 'Indoor-Bike', count: 1, barWeightKg: null, plates: [], maxPlatesPerSide: null },
  {
    id: 'bench_substitute',
    nameDe: 'Bankersatz (Sofa, Stuhl oder Treppenstufe)',
    count: 1,
    barWeightKg: null,
    plates: [],
    maxPlatesPerSide: null,
  },
]

type ExerciseSeed = Omit<Exercise, 'nextVariantText' | 'cueText'> & { nextVariantText?: string; cueText?: string }

const exercise = (seed: ExerciseSeed): Exercise => ({ nextVariantText: null, cueText: '', ...seed })

export const SEED_EXERCISES: Exercise[] = [
  exercise({
    id: 'front_squat_db',
    nameDe: 'Front Squat mit 2 Kurzhanteln',
    movementPattern: 'Knie (Squat)',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'cap',
    nextVariantText: 'Front Squat mit 1½ Wiederholungen',
  }),
  exercise({
    id: 'goblet_squat',
    nameDe: 'Goblet Squat',
    movementPattern: 'Knie (Squat)',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 1,
    startLoadHint: 'cap',
  }),
  exercise({
    id: 'bulgarian_split_squat',
    nameDe: 'Bulgarian Split Squat',
    movementPattern: 'Knie (einbeinig)',
    equipmentIds: ['dumbbell', 'bench_substitute'],
    isUnilateral: true,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
    nextVariantText: 'Vorderfuß erhöht',
  }),
  exercise({
    id: 'pushup_feet_elevated',
    nameDe: 'Liegestütze, Füße erhöht',
    movementPattern: 'Druck horizontal',
    equipmentIds: ['bench_substitute'],
    isUnilateral: false,
    loadType: 'koerpergewicht',
    dumbbellsUsed: 0,
    startLoadHint: null,
    nextVariantText: 'mit Rucksack als Zusatzlast',
  }),
  exercise({
    id: 'floor_press',
    nameDe: 'Floor Press',
    movementPattern: 'Druck horizontal',
    equipmentIds: ['dumbbell', 'mat'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'cap',
  }),
  exercise({
    id: 'row_one_arm',
    nameDe: 'Einarmiges Kurzhantelrudern',
    movementPattern: 'Zug horizontal',
    equipmentIds: ['dumbbell', 'bench_substitute'],
    isUnilateral: true,
    loadType: 'hantel',
    dumbbellsUsed: 1,
    startLoadHint: 'cap',
  }),
  exercise({
    id: 'pullup',
    nameDe: 'Klimmzug',
    movementPattern: 'Zug vertikal',
    equipmentIds: ['pullup_bar'],
    isUnilateral: false,
    loadType: 'koerpergewicht',
    dumbbellsUsed: 0,
    startLoadHint: null,
  }),
  exercise({
    id: 'lateral_raise',
    nameDe: 'Seitheben',
    movementPattern: 'Schulter Abduktion',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
  }),
  exercise({
    id: 'triceps_overhead',
    nameDe: 'Überkopf-Trizepsdrücken',
    movementPattern: 'Ellbogen Extension',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 1,
    startLoadHint: 'calibrate',
  }),
  exercise({
    id: 'hanging_knee_raise',
    nameDe: 'Knieheben im Hang',
    movementPattern: 'Rumpf (Hüftbeugung)',
    equipmentIds: ['pullup_bar'],
    isUnilateral: false,
    loadType: 'koerpergewicht',
    dumbbellsUsed: 0,
    startLoadHint: null,
  }),
  exercise({
    id: 'plank',
    nameDe: 'Plank',
    movementPattern: 'Rumpf Anti-Extension',
    equipmentIds: ['mat'],
    isUnilateral: false,
    loadType: 'zeit',
    dumbbellsUsed: 0,
    startLoadHint: null,
  }),
  exercise({
    id: 'side_plank',
    nameDe: 'Side Plank',
    movementPattern: 'Rumpf Anti-Lateralflexion',
    equipmentIds: ['mat'],
    isUnilateral: true,
    loadType: 'zeit',
    dumbbellsUsed: 0,
    startLoadHint: null,
  }),
  exercise({
    id: 'rdl_single_leg',
    nameDe: 'Einbeiniges Rumänisches Kreuzheben',
    movementPattern: 'Hüfte (Hinge)',
    equipmentIds: ['dumbbell'],
    isUnilateral: true,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
    nextVariantText: 'Standfuß erhöht',
  }),
  exercise({
    id: 'glute_bridge_single_leg',
    nameDe: 'Einbeinige Glute Bridge',
    movementPattern: 'Hüfte (Extension)',
    equipmentIds: ['dumbbell'],
    isUnilateral: true,
    loadType: 'hantel',
    dumbbellsUsed: 1,
    startLoadHint: 'cap',
    nextVariantText: 'einbeiniger Hip Thrust, Schultern auf dem Sofa',
  }),
  exercise({
    id: 'reverse_fly',
    nameDe: 'Reverse Fly vorgebeugt',
    movementPattern: 'Zug horizontal (hintere Schulter)',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
  }),
  exercise({
    id: 'shoulder_press_kneeling',
    nameDe: 'Schulterdrücken kniend',
    movementPattern: 'Druck vertikal',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
  }),
  exercise({
    id: 'biceps_curl',
    nameDe: 'Bizeps Curls',
    movementPattern: 'Ellbogen Flexion',
    equipmentIds: ['dumbbell'],
    isUnilateral: false,
    loadType: 'hantel',
    dumbbellsUsed: 2,
    startLoadHint: 'calibrate',
  }),
  exercise({
    id: 'calf_raise_single_leg',
    nameDe: 'Wadenheben einbeinig',
    movementPattern: 'Wade',
    equipmentIds: ['dumbbell'],
    isUnilateral: true,
    loadType: 'hantel',
    dumbbellsUsed: 1,
    startLoadHint: 'cap',
    nextVariantText: 'auf der Treppenstufe mit voller Dehnung',
  }),
  exercise({
    id: 'dead_bug',
    nameDe: 'Dead Bug',
    movementPattern: 'Rumpf Anti-Extension',
    equipmentIds: ['mat'],
    isUnilateral: true,
    loadType: 'koerpergewicht',
    dumbbellsUsed: 0,
    startLoadHint: null,
  }),
]

export const SEED_TEMPLATES: WorkoutTemplate[] = [
  { id: 'A_lang', type: 'straight_sets', estimatedMinutes: 60, countsForProgression: true },
  { id: 'B_lang', type: 'straight_sets', estimatedMinutes: 60, countsForProgression: true },
  { id: 'kurzzirkel', type: 'circuit', estimatedMinutes: 25, countsForProgression: false },
  { id: 'reisezirkel', type: 'circuit', estimatedMinutes: 25, countsForProgression: false },
  { id: 'bike_z2', type: 'cardio', estimatedMinutes: 45, countsForProgression: false },
]

type ItemRow = [
  exerciseId: string,
  sets: number,
  repMin: number | null,
  repMax: number | null,
  restSeconds: number,
  note?: string,
  withoutLoad?: boolean,
]

const items = (templateId: TemplateId, rows: ItemRow[]): TemplateItem[] =>
  rows.map(([exerciseId, sets, repMin, repMax, restSeconds, note = '', withoutLoad = false], index) => ({
    id: `${templateId}-${index + 1}`,
    templateId,
    exerciseId,
    order: index + 1,
    sets,
    repMin,
    repMax,
    restSeconds,
    note,
    withoutLoad,
  }))

export const SEED_TEMPLATE_ITEMS: TemplateItem[] = [
  ...items('A_lang', [
    ['front_squat_db', 4, 10, 15, 90, '3 s ablassen, 1 s Pause unten'],
    ['bulgarian_split_squat', 3, 10, 12, 60, 'stärkster Beinreiz im Plan'],
    ['pushup_feet_elevated', 3, 8, 15, 60, 'Hanteln als Griffe für mehr Tiefe'],
    ['floor_press', 3, 12, 15, 60, 'Ellbogen kurz am Boden absetzen'],
    ['row_one_arm', 3, 12, 15, 45, '1 s Halten in der Endposition'],
    ['lateral_raise', 3, 12, 15, 45],
    ['triceps_overhead', 2, 12, 15, 45],
    ['hanging_knee_raise', 2, 8, 12, 45, 'ohne Schwung'],
    ['side_plank', 2, 40, 40, 30],
  ]),
  ...items('B_lang', [
    ['rdl_single_leg', 4, 10, 12, 75, '3 s ablassen'],
    ['pullup', 4, null, null, 90, 'nach Einstufung'],
    ['glute_bridge_single_leg', 3, 12, 15, 60, 'Hantel auf der Hüfte'],
    ['row_one_arm', 3, 12, 15, 60],
    ['reverse_fly', 2, 12, 15, 45],
    ['shoulder_press_kneeling', 3, 10, 15, 60, 'kniend verhindert das Ausweichen ins Hohlkreuz'],
    ['biceps_curl', 2, 12, 15, 45],
    ['calf_raise_single_leg', 2, 15, 20, 30],
    ['dead_bug', 2, 10, 10, 30],
  ]),
  // Circuits: four rounds, no rest within a round, 45 s between rounds.
  ...items('kurzzirkel', [
    ['goblet_squat', 4, 12, 15, 0],
    ['pushup_feet_elevated', 4, 12, 15, 0],
    ['row_one_arm', 4, 12, 15, 0],
    ['glute_bridge_single_leg', 4, 12, 15, 45],
  ]),
  ...items('reisezirkel', [
    ['bulgarian_split_squat', 4, 12, 15, 0, 'ohne Last, hinterer Fuß auf Bett oder Stuhl', true],
    ['pushup_feet_elevated', 4, 8, 15, 0],
    ['glute_bridge_single_leg', 4, 15, 20, 0, 'ohne Last', true],
    ['side_plank', 4, 40, 40, 45],
  ]),
]
